name: Daily_Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}


jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community, repositories
          plugin_wakatime: yes
          plugin_wakatime_sections: languages-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: html, css, js, renderscript
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
