name: Daily_Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}


jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community, repositories
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: iGxnon, igxnon@gmail.com, 918845478@qq.com, igxnon@users.noreply.github.com
          plugin_languages_ignored: html, css, js, renderscript, dockerfile, makefile, jupyter notebook
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_wakatime: yes
          plugin_wakatime_sections: time
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
